const express=require('express');
const router=express.Router();
const {auth,isInstructor}=require('../Middleware/auth');
const {updateProfile,deleteprofile,getalldetails,updateDisplyaPicture,getEnrolledCourses,instructorDashboard}=require('../Controller/Profile');
router.put('/updateProfile',auth,updateProfile);
router.delete('/deleteProfile',auth,deleteprofile);
router.get('/getUserDetails',auth,getalldetails);
router.put('/updateDisplayPicture',auth,updateDisplyaPicture);
router.get('/getEnrolledCourses',auth,getEnrolledCourses);
router.get('/instructorDashboard',auth,isInstructor,instructorDashboard);
module.exports=router;